<?php

declare(strict_types=1);

namespace App\Livewire\Report;

use App\Models\Report;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Support\Enums\MaxWidth;
use Filament\Tables;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Contracts\View\View;
use Shopper\Livewire\Pages\AbstractPageComponent;

class Index extends AbstractPageComponent implements HasForms, HasTable
{
    use InteractsWithForms;
    use InteractsWithTable;

    public function mount(): void
    {
        $this->authorize('viewAny', Report::class);
    }

    public function table(Table $table): Table
    {
        return $table
            ->query(
                Report::query()
                    ->with('generatedBy')
                    ->latest('generated_at')
            )
            ->columns([
                Tables\Columns\TextColumn::make('title')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('type')
                    ->badge()
                    ->colors([
                        'success' => 'sales',
                        'warning' => 'commissions',
                        'info' => 'deliveries',
                        'gray' => 'inventory',
                    ])
                    ->sortable(),
                Tables\Columns\TextColumn::make('period_start')
                    ->label('Start')
                    ->date()
                    ->placeholder('All time')
                    ->sortable(),
                Tables\Columns\TextColumn::make('period_end')
                    ->label('End')
                    ->date()
                    ->placeholder('All time')
                    ->sortable(),
                Tables\Columns\TextColumn::make('generatedBy.full_name')
                    ->label('Generated By')
                    ->placeholder('System')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('generated_at')
                    ->dateTime()
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('type')
                    ->options([
                        'sales' => 'Sales',
                        'commissions' => 'Commissions',
                        'deliveries' => 'Deliveries',
                        'inventory' => 'Inventory',
                    ]),
            ])
            ->actions([
                Tables\Actions\Action::make('delete')
                    ->label('Delete')
                    ->icon('heroicon-o-trash')
                    ->color('danger')
                    ->requiresConfirmation()
                    ->visible(fn (Report $record): bool => auth()->user()?->can('delete', $record) ?? false)
                    ->authorize(fn (Report $record): bool => auth()->user()?->can('delete', $record) ?? false)
                    ->action(fn (Report $record) => $record->delete()),
            ])
            ->filtersFormWidth(MaxWidth::Medium);
    }

    public function render(): View
    {
        return view('livewire.report.index', [
            'latestReport' => Report::query()->latest('generated_at')->first(),
        ])->title('Reports');
    }
}
